version: '3.9'

services:

  # FHE ALL-IN-ONE
  fhe-all-in-one:
    build: ./enc
    container_name: fhe-aio
    volumes:
      - /home/nima/paper/datasets/:/bdt/build/tee_data
    command: tail -f /dev/null
    networks:
      - soteria_network

networks:
  soteria_network:
    name: "soteria_network"

